version: '3.4'

services:
  flaskpatreon:
    image: flaskpatreon
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 65010:65010
    environment:
      - FLASK_APP=pat_test.py
      - CONFIG=myconfig.py