version: '3.4'

services:
  flaskpatreon:
    image: flaskpatreon
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 65010"]
    ports:
      - 65010:65010
      - 5678:5678
    environment:
      - FLASK_APP=pat_test.py
      - CONFIG=myconfig.py
