version: '3.4'

services:
  flaskpatreon:
    image: whipcarte/flaskpatreon
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 65010:65010
    environment:
      - FLASK_APP=pat_test.py
      - CONFIG=config.py
  flaskpatreon_aws:
    image: whipcarte/flaskpatreon:aws
    build:
      context: .
      dockerfile: ./Dockerfile-2.Dockerfile
    environment:
      - FLASK_APP=pat_test.py
      - CONFIG=config.py